package com.intent.guard.core;

import androidx.annotation.NonNull;

import java.security.SecureRandom;

/**
 * Represents a session utility that generates secure, random session codes.
 *
 * <p>
 * A {@code Session} provides a way to generate unique session identifiers
 * using a customizable character set and code length. It supports a delegation
 * mechanism through the {@link #replace(Session)} method, allowing an existing
 * session to adopt the configuration of a newer instance.
 * </p>
 *
 * <h3>Usage</h3>
 * <pre>{@code
 * // Create a session with default characters and length 12
 * Session session = new Session(12);
 *
 * // Generate a new secure session code
 * String code = session.generateSessionCode();
 *
 * // Replace session with another configuration (length 20, custom charset)
 * Session newSession = new Session("ABCD123", 20);
 * session.replace(newSession);
 *
 * // Now generates codes based on the new session configuration
 * String newCode = session.generateSessionCode();
 * }</pre>
 *
 * @since 1.0
 * @author David Onyia
 */
public final class Session {

    private final SecureRandom random = new SecureRandom();
    private final String characters;
    private final int codeLength;
    private boolean isGenerated;
    private Session delegate;

    /**
     * Creates a session with a default character set and a given code length.
     * <p>
     * Default character set: {@code "mnbvcxzasdfghjklpoiuytrewq1234567890_"}
     * </p>
     *
     * @param codeLength The length of the session code to generate (minimum 7).
     */
    public Session(int codeLength) {
        this("mnbvcxzasdfghjklpoiuytrewq1234567890_", codeLength);
    }

    /**
     * Creates a session with a custom character set and code length.
     *
     * @param characters The characters allowed in the session code (cannot be empty).
     * @param codeLength The length of the session code to generate (minimum 7).
     * @throws IllegalArgumentException If characters string is empty.
     */
    public Session(@NonNull String characters, int codeLength) {

        if (characters.isEmpty()) {
            throw new IllegalArgumentException("Character set cannot be empty");
        }

        this.characters = characters;
        this.codeLength = Math.max(codeLength, 7);
    }

    /**
     * Replaces this session's configuration with a new one by delegating all future
     * calls to the provided session instance.
     *
     * <p>
     * This method includes logic to collapse delegation chains, ensuring that
     * deeply nested replacements resolve directly to the root active session.
     * </p>
     *
     * @param newSession The new session instance to delegate to.
     * @throws IllegalArgumentException If attempting to replace a session with itself.
     */
    public void replace(@NonNull Session newSession) {
        if (this == newSession) {
            throw new IllegalArgumentException("Cannot replace a session with itself");
        }

        // Collapse delegation chain to avoid deep recursion
        Session root = newSession;
        while (root.delegate != null) {
            root = root.delegate;
        }

        this.delegate = root;
    }

    /**
     * Indicates whether a session code has been generated by this session
     * or its delegate.
     *
     * @return {@code true} if a code has been generated; otherwise {@code false}.
     */
    public boolean isGenerated() {
        return delegate != null ? delegate.isGenerated : isGenerated;
    }

    /**
     * Returns the configured length for session codes.
     * * @return The integer length of generated codes.
     */
    public int getCodeLength() {
        return delegate != null ? delegate.codeLength : codeLength;
    }

    /**
     * Generates a new session code using the configured character set and length.
     * <p>
     * This operation uses {@link SecureRandom} to ensure the generated code is
     * cryptographically strong and unpredictable.
     * </p>
     *
     * @return A unique, randomly generated session code string.
     */
    @NonNull
    public String generateSessionCode() {
        return delegate != null
                ? delegate.generateSessionCodeInternal(delegate.codeLength)
                : generateSessionCodeInternal(codeLength);
    }

    /**
     * Internal implementation of the code generation logic.
     *
     * @param codeLength The length of the code to construct.
     * @return The generated string.
     */
    @NonNull
    private String generateSessionCodeInternal(int codeLength) {

        StringBuilder str = new StringBuilder(codeLength);

        for (int j = 0; j < codeLength; j++) {
            str.append(characters.charAt(random.nextInt(characters.length())));
        }

        isGenerated = true;
        return str.toString();
    }
}